# Generated by Django 3.1.4 on 2020-12-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Browser'),
        ),
    ]
