# Generated by Django 3.1.4 on 2020-12-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Celery ID'),
        ),
    ]
